theme: jekyll-theme-cayman
title: Discover® Deals and Cashback Rewards Notifier
description: A Chrome Extension that shows a notification when visiting sites that qualify for Discover® Deals or Cashback Rewards.
show_downloads: false
destination: ../build/docs